const {registerAdmin,
    adminSignIn,
    adminSignOut,
    verifyOfficial,
    getOfficials,
    declineOfficial,
    updatePassword
}=require("./admin.controller");
const {
   registerOfficial,
    officialSignIn,
    officialSignOut,
    updatePasswordOfficial,
    uploadData,
    verifyData,
    getPendingHighRiskReports,
    rejectData,
    getOfficialProfile
}=require("./official.controller")
module.exports={registerAdmin,
    adminSignIn,
    adminSignOut,
    verifyOfficial,
    getOfficials,
    declineOfficial,
    updatePassword,
    registerOfficial,
    officialSignIn,
    officialSignOut,
    updatePasswordOfficial,
    uploadData,
    verifyData,
    getPendingHighRiskReports,
    rejectData,
    getOfficialProfile
};